name: ci

on:
  push:
    branches:
      - "**"

jobs:
  test:
    name: test
    runs-on: "ubuntu-24.04"

    strategy:
      matrix:
        include:
          - php-version: 8.3
          - php-version: 8.4

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: PHP
        uses: ./.github/actions/setup-php
        with:
          php-version: "${{ matrix.php-version }}"
      - name: tests
        run: make test
